name: Nightly build and test

on:
  schedule:
    - cron: '42 0 * * *'

jobs:
  build:

    runs-on: macos-15

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
