name: Nightly build and test

on:
  schedule:
    - cron: '42 0 * * *'

jobs:
  build:

    runs-on: macos-26

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
