name: Merge or commit

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
